# Generated by Django 3.2.3 on 2021-06-12 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Account', '0003_auto_20210611_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
