# Generated by Django 3.2.3 on 2021-06-14 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_Account', '0007_delete_verifyorgbankdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifyOrgBankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(blank=True, max_length=255)),
                ('bank_branch', models.CharField(blank=True, max_length=255)),
                ('account_number', models.CharField(blank=True, max_length=30)),
                ('account_name', models.CharField(blank=True, max_length=100)),
                ('current_balance', models.IntegerField(default=0)),
                ('total_withdraw', models.IntegerField(default=0)),
                ('total_collection', models.IntegerField(default=0)),
                ('is_verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
