# Generated by Django 3.2.3 on 2021-06-15 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Account', '0008_verifyorgbankdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='thana',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='zilla',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
