# Generated by Django 3.2.3 on 2021-06-16 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Account', '0009_auto_20210615_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='given_ord_details',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='org_documents_given',
            field=models.BooleanField(default=False),
        ),
    ]
