# Generated by Django 3.2.3 on 2021-06-16 12:42

import App_Account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Account', '0011_auto_20210616_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='member1_nid_back',
            field=models.ImageField(blank=True, upload_to=App_Account.models.upload_to_org_member1_nid_back),
        ),
        migrations.AlterField(
            model_name='organization',
            name='member1_nid_front',
            field=models.ImageField(blank=True, upload_to=App_Account.models.upload_to_member1_nid_front),
        ),
        migrations.AlterField(
            model_name='organization',
            name='member2_nid_back',
            field=models.ImageField(blank=True, upload_to=App_Account.models.upload_to_org_member2_nid_back),
        ),
        migrations.AlterField(
            model_name='organization',
            name='member2_nid_front',
            field=models.ImageField(blank=True, upload_to=App_Account.models.upload_to_org_member2_nid_front),
        ),
        migrations.AlterField(
            model_name='organization',
            name='org_pic',
            field=models.ImageField(blank=True, upload_to=App_Account.models.upload_to_org_pic),
        ),
        migrations.AlterField(
            model_name='organization',
            name='org_prove1',
            field=models.ImageField(blank=True, upload_to=App_Account.models.upload_to_org_org_prove1),
        ),
        migrations.AlterField(
            model_name='organization',
            name='org_prove2',
            field=models.ImageField(blank=True, upload_to=App_Account.models.upload_to_org_org_prove2),
        ),
    ]
