# Generated by Django 3.2.3 on 2021-06-23 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Account', '0014_alter_organization_org_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='message',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
