# Generated by Django 3.2.3 on 2021-06-26 05:14

import App_Account.models
from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('App_Account', '0016_organization_banned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='org_prove1',
            field=models.ImageField(blank=True, null=True, upload_to=App_Account.models.upload_to_org_org_prove1),
        ),
        migrations.AlterField(
            model_name='organization',
            name='org_prove2',
            field=models.ImageField(blank=True, null=True, upload_to=App_Account.models.upload_to_org_org_prove2),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], default='default_pic.png', force_format=None, keep_meta=True, null=True, quality=100, size=[293, 313], upload_to=App_Account.models.upload_to_org_pic),
        ),
    ]
