# Generated by Django 3.2.3 on 2021-06-26 05:16

import App_Account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Account', '0017_auto_20210626_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='org_prove1',
            field=models.ImageField(blank=True, default='default_pic.jpeg', null=True, upload_to=App_Account.models.upload_to_org_org_prove1),
        ),
        migrations.AlterField(
            model_name='organization',
            name='org_prove2',
            field=models.ImageField(blank=True, default='default_pic.jpeg', null=True, upload_to=App_Account.models.upload_to_org_org_prove2),
        ),
    ]
