# Generated by Django 3.2.3 on 2021-06-26 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Account', '0019_auto_20210626_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifypersonbankdetails',
            name='filled',
            field=models.BooleanField(default=False),
        ),
    ]
