# Generated by Django 3.2.3 on 2021-06-30 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Account', '0021_verifypersonbankdetails_is_personorg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verifypersonbankdetails',
            name='is_personorg',
        ),
    ]
