# Generated by Django 3.2.3 on 2021-06-30 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Account', '0022_remove_verifypersonbankdetails_is_personorg'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifypersonbankdetails',
            name='message',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
