# Generated by Django 3.2.3 on 2021-07-06 15:35

import App_Account.models
from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('App_Account', '0023_verifypersonbankdetails_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], default='default_pic.png', force_format=None, keep_meta=True, null=True, quality=100, size=[293, 313], upload_to=App_Account.models.upload_to_profile_pic),
        ),
    ]
