# Generated by Django 3.2.3 on 2021-07-07 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Account', '0024_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='message',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
