# Generated by Django 3.2.3 on 2021-07-09 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Account', '0025_profile_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifypersonbankdetails',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
