# Generated by Django 3.2.3 on 2021-06-20 11:01

import App_Event.models
import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CreateEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('need_amount', models.IntegerField(default=100000)),
                ('collected', models.IntegerField(default=0)),
                ('event_pic', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], default='event_image_main.png', force_format=None, keep_meta=True, null=True, quality=100, size=[1200, 630], upload_to=App_Event.models.upload_to_event)),
                ('sort_description', models.CharField(blank=True, max_length=255)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('percentage', models.IntegerField(default=4.5)),
                ('endtime', models.DateTimeField(default=App_Event.models.get_deadline)),
                ('terms_and_condition', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('banned', models.BooleanField(default=False)),
                ('message', models.TextField(blank=True, null=True)),
                ('clicked', models.IntegerField(default=0)),
                ('keywords', models.TextField(blank=True)),
                ('extra_img1', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], default='event_image_main.png', force_format=None, keep_meta=True, null=True, quality=100, size=[1200, 630], upload_to=App_Event.models.upload_to_event_extraimage)),
                ('extra_img2', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], default='event_image_main.png', force_format=None, keep_meta=True, null=True, quality=100, size=[1200, 630], upload_to=App_Event.models.upload_to_event_extraimage)),
                ('event_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='App_Event.eventtype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
