# Generated by Django 3.2.3 on 2021-06-21 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Event', '0002_alter_createevent_need_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='createevent',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
