# Generated by Django 3.2.3 on 2021-06-21 10:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App_Event', '0003_createevent_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CreateEvent',
            new_name='Event',
        ),
    ]
