# Generated by Django 3.2.3 on 2021-06-22 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Event', '0006_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='orderId',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donation',
            name='paymentId',
            field=models.CharField(blank=True, max_length=264, null=True),
        ),
    ]
