# Generated by Django 3.2.3 on 2021-06-23 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Event', '0007_auto_20210622_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='message',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
