# Generated by Django 3.2.3 on 2021-06-28 16:52

import App_Event.models
from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('App_Event', '0011_withdraw_confirm'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_pic_thumb',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], default='event_image_main.png', force_format=None, keep_meta=True, null=True, quality=100, size=[362, 215], upload_to=App_Event.models.upload_to_event),
        ),
    ]
