# Generated by Django 3.2.3 on 2021-06-28 12:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommonField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contactnumber', models.CharField(blank=True, max_length=20, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo')),
                ('facebook', models.TextField(blank=True, null=True)),
                ('twitter', models.TextField(blank=True, null=True)),
                ('youtube', models.TextField(blank=True, null=True)),
                ('other1', models.TextField(blank=True, null=True)),
                ('other2', models.TextField(blank=True, null=True)),
                ('footerLogo', models.ImageField(blank=True, null=True, upload_to='logo')),
                ('footernote', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mainTitle', models.CharField(blank=True, max_length=255, null=True)),
                ('sortTitle', models.CharField(blank=True, max_length=255, null=True)),
                ('backgroundImage', models.ImageField(upload_to='landing_page')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
