# Generated by Django 3.2.3 on 2021-06-29 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Admin', '0004_supportedbanks'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportedbanks',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
