# Generated by Django 3.2.3 on 2021-07-01 04:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('App_Admin', '0006_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='issue',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
