# Generated by Django 3.2.3 on 2021-07-01 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Admin', '0008_contactus_contacted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='contacted',
            field=models.BooleanField(default=False),
        ),
    ]
